// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoAY4FiMr6sqesQpdJe3O95SbBjOxj89M',
    appId: '1:387316402526:web:46637d44ac238878e867cf',
    messagingSenderId: '387316402526',
    projectId: 'mywebapp-b8e3d',
    authDomain: 'mywebapp-b8e3d.firebaseapp.com',
    storageBucket: 'mywebapp-b8e3d.appspot.com',
    measurementId: 'G-4R3WV7677S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jp2T8yfteU_uS4sra7So4NzXk6wRFTg',
    appId: '1:387316402526:android:b2186111029b1f8ce867cf',
    messagingSenderId: '387316402526',
    projectId: 'mywebapp-b8e3d',
    storageBucket: 'mywebapp-b8e3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApMoAnQRX3k3L-HsHY7iwel_IViMwnabM',
    appId: '1:387316402526:ios:01604441141d65bae867cf',
    messagingSenderId: '387316402526',
    projectId: 'mywebapp-b8e3d',
    storageBucket: 'mywebapp-b8e3d.appspot.com',
    iosClientId: '387316402526-kuq7i7d7h4rjrjle46tq7admvm712ar8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApMoAnQRX3k3L-HsHY7iwel_IViMwnabM',
    appId: '1:387316402526:ios:26ef28cf897978fae867cf',
    messagingSenderId: '387316402526',
    projectId: 'mywebapp-b8e3d',
    storageBucket: 'mywebapp-b8e3d.appspot.com',
    iosClientId: '387316402526-a2ildla4grg3ltsa36s51qrkt0phog1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebapp.RunnerTests',
  );
}
